// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCekCCP99l9lR_fG_ky5OUS0b6EPAyltkA',
    appId: '1:614485048976:web:c33293a5195f8db81a6215',
    messagingSenderId: '614485048976',
    projectId: 'qrapp1-e24e4',
    authDomain: 'qrapp1-e24e4.firebaseapp.com',
    databaseURL: 'https://qrapp1-e24e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qrapp1-e24e4.appspot.com',
    measurementId: 'G-2ZLBV70J9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCA-0xD6eXBWqfjPdG0TQEYbvzRNmQrmk',
    appId: '1:614485048976:android:eb41b29250ac08fa1a6215',
    messagingSenderId: '614485048976',
    projectId: 'qrapp1-e24e4',
    databaseURL: 'https://qrapp1-e24e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qrapp1-e24e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzeMvBR9ud0p62V2OMeHuqni1bq0s1HtM',
    appId: '1:614485048976:ios:7e36f9ca291dc7e71a6215',
    messagingSenderId: '614485048976',
    projectId: 'qrapp1-e24e4',
    databaseURL: 'https://qrapp1-e24e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qrapp1-e24e4.appspot.com',
    iosBundleId: 'com.example.qrapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzeMvBR9ud0p62V2OMeHuqni1bq0s1HtM',
    appId: '1:614485048976:ios:3f4d6b3fe7d1bb131a6215',
    messagingSenderId: '614485048976',
    projectId: 'qrapp1-e24e4',
    databaseURL: 'https://qrapp1-e24e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'qrapp1-e24e4.appspot.com',
    iosBundleId: 'com.example.qrapp1.RunnerTests',
  );
}
